### ISSUE TITLE
Disqus not showing.

### ISSUE THREAD

**Issue by rikusen0335** [Sommerregen/grav-plugin-jscomments#27]
I just did the settings of 3 steps.

1. Set the .yaml file.
```
enabled: true
active: true
provider: disqus
providers:
  disqus:
    shortname: XXXXXXX
    show_count: true
    language: ja
```
Now I didn't show up shortname.

2. Write an initial setup in `item.html.twig` like this ↓.
```
 <div class="modularitem">
    {# diable regular post handling - hibbittsdesign.org #}
    {# <h3>{{ page.title }}</h3> #}
    <p>{{ page.content }}</p>
    <div>{{ jscomments()|raw }}</div>
  </div>
```

3. And then, I did hard-refresh the browser and clean Grav's cache.

How do I fix it? If any solution exists, I want to know it.

Theme: quark-open-publishing v1.1.5
Grav version: v1.5.1
and running on Raspbian (Debian based)
